// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanLorenzoApi.Data;

#nullable disable

namespace SanLorenzoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanLorenzoApi.Dominio.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradoSeccionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradoSeccionId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Bimestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioEscolar")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bimestres");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Comunicado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("DestinatarioTipo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GradoSeccionId")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolDestino")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("GradoSeccionId");

                    b.ToTable("Comunicados");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.DetalleNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumeroNota")
                        .HasColumnType("int");

                    b.Property<int>("RegistroNotaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroNotaId");

                    b.ToTable("DetallesNotas");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.DocenteAsignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int>("GradoSeccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("GradoSeccionId");

                    b.ToTable("DocenteAsignaturas");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.GradoSeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GradoSecciones");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int>("GradoSeccionId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("GradoSeccionId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.RegistroNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("BimestreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Promedio")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("BimestreId");

                    b.ToTable("RegistrosNotas");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FiltrosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneradoPorId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Alumno", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.GradoSeccion", "GradoSeccion")
                        .WithMany("Alumnos")
                        .HasForeignKey("GradoSeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SanLorenzoApi.Dominio.Usuario", "Usuario")
                        .WithOne("Alumno")
                        .HasForeignKey("SanLorenzoApi.Dominio.Alumno", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradoSeccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Asignatura", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.Curso", "Curso")
                        .WithMany("Asignaturas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Asistencia", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.Alumno", "Alumno")
                        .WithMany("Asistencias")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SanLorenzoApi.Dominio.Asignatura", "Asignatura")
                        .WithMany("Asistencias")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Comunicado", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SanLorenzoApi.Dominio.GradoSeccion", "GradoSeccion")
                        .WithMany()
                        .HasForeignKey("GradoSeccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Autor");

                    b.Navigation("GradoSeccion");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.DetalleNota", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.RegistroNota", "RegistroNota")
                        .WithMany("Detalles")
                        .HasForeignKey("RegistroNotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroNota");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Docente", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.Usuario", "Usuario")
                        .WithOne("Docente")
                        .HasForeignKey("SanLorenzoApi.Dominio.Docente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.DocenteAsignatura", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.Asignatura", "Asignatura")
                        .WithMany("DocenteAsignaturas")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SanLorenzoApi.Dominio.Docente", "Docente")
                        .WithMany("DocenteAsignaturas")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SanLorenzoApi.Dominio.GradoSeccion", "GradoSeccion")
                        .WithMany("DocenteAsignaturas")
                        .HasForeignKey("GradoSeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Docente");

                    b.Navigation("GradoSeccion");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Horario", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SanLorenzoApi.Dominio.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SanLorenzoApi.Dominio.GradoSeccion", "GradoSeccion")
                        .WithMany("Horarios")
                        .HasForeignKey("GradoSeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Docente");

                    b.Navigation("GradoSeccion");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.RegistroNota", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.Alumno", "Alumno")
                        .WithMany("RegistrosNotas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SanLorenzoApi.Dominio.Asignatura", "Asignatura")
                        .WithMany("RegistrosNotas")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SanLorenzoApi.Dominio.Bimestre", "Bimestre")
                        .WithMany("RegistrosNotas")
                        .HasForeignKey("BimestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");

                    b.Navigation("Bimestre");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Reporte", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.Usuario", "GeneradoPor")
                        .WithMany()
                        .HasForeignKey("GeneradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneradoPor");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Tarea", b =>
                {
                    b.HasOne("SanLorenzoApi.Dominio.Asignatura", "Asignatura")
                        .WithMany("Tareas")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Alumno", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("RegistrosNotas");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Asignatura", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("DocenteAsignaturas");

                    b.Navigation("RegistrosNotas");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Bimestre", b =>
                {
                    b.Navigation("RegistrosNotas");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Curso", b =>
                {
                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Docente", b =>
                {
                    b.Navigation("DocenteAsignaturas");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.GradoSeccion", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("DocenteAsignaturas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.RegistroNota", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SanLorenzoApi.Dominio.Usuario", b =>
                {
                    b.Navigation("Alumno");

                    b.Navigation("Docente");
                });
#pragma warning restore 612, 618
        }
    }
}
